name: Build DEB Package

on:
  release:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build DEB package
        run: |
          chmod -R 775 rockpi-quad/DEBIAN/
          dpkg-deb --build -Z gzip rockpi-quad
      - name: Upload DEB package
        uses: actions/upload-artifact@v4
        with:
          name: rockpi-quad.deb
          path: rockpi-quad.deb
